version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # Use default linters: errcheck, govet, ineffassign, staticcheck, unused
  enable-all: false
  disable-all: false

issues:
  exclude-use-default: false
