#!/usr/bin/env bash
# Generates .vscode/settings.local.json with Nix Go paths
# This file is git-ignored and specific to each developer's machine

set -e

echo "🔍 Detecting Nix Go paths..."

GO_PATH=$(nix develop -c which go 2>&1 | grep -E "^/nix/store" | head -1)
GOPLS_PATH=$(nix develop -c which gopls 2>&1 | grep -E "^/nix/store" | head -1)

if [ -z "$GO_PATH" ] || [ -z "$GOPLS_PATH" ]; then
    echo "❌ Failed to get Go paths from Nix environment"
    echo "   Make sure you have run 'nix develop' successfully"
    exit 1
fi

GO_ROOT=$(dirname "$(dirname "$GO_PATH")")

echo "✓ Found paths:"
echo "  Go:    $GO_PATH"
echo "  gopls: $GOPLS_PATH"
echo "  GOROOT: $GO_ROOT"
echo ""

# Generate local settings file
cat > .vscode/settings.local.json <<EOF
{
  // Auto-generated by scripts/setup-cursor-go.sh
  // This file is git-ignored and contains machine-specific Nix paths
  "go.goroot": "$GO_ROOT",
  "go.alternateTools": {
    "go": "$GO_PATH",
    "gopls": "$GOPLS_PATH"
  }
}
EOF

echo "✅ Created .vscode/settings.local.json"
echo ""
echo "📝 Next steps:"
echo "   IMPORTANT: VSCode/Cursor doesn't auto-load settings.local.json!"
echo ""
echo "   Choose ONE of these options:"
echo ""
echo "   Option A (Easiest): Launch Cursor from Nix shell"
echo "     1. Run: nix develop"
echo "     2. Run: cursor ."
echo "     3. Cursor inherits Nix environment automatically!"
echo ""
echo "   Option B: Add settings to your User Settings"
echo "     1. Open the generated .vscode/settings.local.json"
echo "     2. Copy the settings"
echo "     3. Cmd+Shift+P → 'Preferences: Open User Settings (JSON)'"
echo "     4. Paste the settings there"
echo "     5. Reload window"
echo ""
echo "   Option C: Install direnv extension"
echo "     1. Install 'direnv' extension in Cursor"
echo "     2. Install direnv on your system"
echo "     3. Reload - environment loads automatically!"
echo ""
echo "See docs/VSCODE_SETUP.md for more details."
